apiVersion: v1
kind: "Template"
metadata:
  name: apiman-dev-build-template
  annotations:
    description: "Template for creating local builds of apiman components from source."
    tags: "infrastructure"
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: origin
    name: origin
  spec:
    dockerImageRepository: openshift/origin:latest
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: apiman-elasticsearch
    name: centos
  spec:
    dockerImageRepository: library/centos:7
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: apiman-deployer
    name: apiman-deployer
  spec: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: apiman-elasticsearch
    name: apiman-elasticsearch
  spec: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: apiman-curator
    name: apiman-curator
  spec: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: apiman-builder
    name: apiman-builder
  spec: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: apiman-console
    name: apiman-console
  spec: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: apiman-gateway
    name: apiman-gateway
  spec: {}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: apiman-deployer
    name: apiman-deployer
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: apiman-deployer:latest
    resources: {}
    source:
      contextDir: deployer
      git:
        uri: ${APIMAN_FORK_URL}
        ref: ${APIMAN_FORK_BRANCH}
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: origin:latest
      type: Docker
    triggers:
    - type: ConfigChange
    - type: ImageChange
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: apiman-elasticsearch
    name: apiman-elasticsearch
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: apiman-elasticsearch:latest
    resources: {}
    source:
      contextDir: deployer/common/elasticsearch
      git:
        uri: ${APIMAN_FORK_URL}
        ref: ${APIMAN_FORK_BRANCH}
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: centos:7
      type: Docker
    triggers:
    - type: ConfigChange
    - type: ImageChange
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: apiman-curator
    name: apiman-curator
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: apiman-curator:latest
    resources: {}
    source:
      contextDir: deployer/common/curator
      git:
        uri: ${APIMAN_FORK_URL}
        ref: ${APIMAN_FORK_BRANCH}
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: DockerImage
          name: openshift/base-centos7
      type: Docker
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: apiman-builder
    name: apiman-builder
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: apiman-builder:latest
    resources: {}
    source:
      contextDir: apiman-builder
      git:
        uri: ${APIMAN_FORK_URL}
        ref: ${APIMAN_FORK_BRANCH}
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: DockerImage
          name: openshift/base-centos7
      type: Docker
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: apiman-console
    name: apiman-console
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: apiman-console:latest
    resources: {}
    source:
      contextDir: apiman
      git:
        uri: ${F8_FORK_URL}
        ref: ${F8_FORK_BRANCH}
      type: Git
    strategy:
      type: Custom
      customStrategy:
        exposeDockerSocket: true
        from:
          kind: ImageStreamTag
          name: apiman-builder:latest
    triggers:
    - type: ConfigChange
    - type: ImageChange
      from:
        kind: ImageStreamTag
        name: apiman-builder:latest
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: apiman-gateway
    name: apiman-gateway
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: apiman-gateway:latest
    resources: {}
    source:
      contextDir: apiman-gateway
      git:
        uri: ${F8_FORK_URL}
        ref: ${F8_FORK_BRANCH}
      type: Git
    strategy:
      type: Custom
      customStrategy:
        exposeDockerSocket: true
        from:
          kind: ImageStreamTag
          name: apiman-builder:latest
    triggers:
    - type: ConfigChange
    - type: ImageChange
      from:
        kind: ImageStreamTag
        name: apiman-builder:latest
parameters:
-
  description: 'URL for origin-apiman fork'
  name: APIMAN_FORK_URL
  value: https://github.com/ll911/origin-apiman
-
  description: 'branch for origin-apiman fork'
  name: APIMAN_FORK_BRANCH
  value: master
-
  description: 'URL for fabric8-ipaas fork'
  name: F8_FORK_URL
  value: https://github.com/fabric8io/fabric8-ipaas
-
  description: 'branch for fabric8-ipaas fork'
  name: F8_FORK_BRANCH
  value: master
